spring.boot:
    priority: 1
    auto-configuration:
        org.lamisplus.modules.bootstrap.configurer.DynamicModuleImportConfigurer: true
        org.lamisplus.modules.bootstrap.module.ApplicationProperties: true
        org.lamisplus.modules.bootstrap.module.ModuleFileStorageService: true
