applicationInfo:
  applicationId: lamisplus
  applicationName: LAMISPLUS
  buildDate: "@maven.build.timestamp@"
  buildId: "@pom.version@-@build.revision@"
build:
  number: "@build.revision@"
logging:
  request-response:
    enabled: true
  file:
    name: application-debug.log
server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace:
      facility: false
  datasource:
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  http2:
    enabled: true
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 20s
spring:
  datasource:
    username: xjwygrdeaarjol
    password: 8c46a597ab716c2161e3ec4837afc803c84fbf31d2883fd82c6080cb71ea4885
    url: jdbc:postgresql://ec2-34-206-252-187.compute-1.amazonaws.com:5432/d7289uqovjkusm
    driver-class-name: org.postgresql.Driver
    hibernate:
      event.merge.enty_copy_observer: allow
    hikari:
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximum-pool-size: 60
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.enable_lazy_load_no_trans: true

  mail:
    host: localhost
    port: 25
    username:
    password:
    jndi-name:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    jackson:
      serialization:
        fail-on-empty-beans: false
  banner:
    location: banner.txt
jhipster:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: YzMzNjBmOTcwN2Y4YmNmNWViMzhhNjk5MjhmMmY5OTZkNWUxYzIwM2Q5ZWU4OWIzNTZmZTBlOTMzZjFhN2ZmMzBlMDIzMGRkYWNkYTIwOThmY2E1ZjNhYTAxODA0NTJkY2U5NTYxZTI1YjA1NTIyN2IwMTZlMTRlMDM0OTIyNzM=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
lamis:
  temp-dir: runtime/
  module-path: modules